version: '3.8'

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - my_network
  rest-api:
    depends_on:
      - mongo_db
    image: tcarisland/tcapi:latest
    container_name: spring-boot-app
    ports:
      - "8082:8082"
    networks:
      - my_network
  frontend:
    image: tcarisland/tcclient
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    
volumes:
  db:
