apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: clientservice
  name: clientservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clientservice
  template:
    metadata:
      labels:
        io.kompose.network/docker-mynetwork: "true"
        io.kompose.service: clientservice
    spec:
      containers:
        - image: tcarisland/tcclient
          name: nextjs-app
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
