apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dbservice
  name: dbservice
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: dbservice
