version: '3.8'

services:
  dbservice:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - mynetwork
  apiservice:
    depends_on:
      - dbservice
    image: tcarisland/tcapi:latest
    container_name: spring-boot-app
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/tcapi"
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  clientservice:
    depends_on:
      - apiservice
    image: tcarisland/tcclient:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    
volumes:
  db:
