version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    networks:
      - mynetwork
  tcapi:
    depends_on:
      - mongodb
    image: tcarisland/tcapi:latest
    container_name: tcapi
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/tcapi"
    ports:
      - "8080:8080"
    networks:
      - mynetwork
  client:
    depends_on:
      - tcapi
    image: tcarisland/tcclient:latest
    container_name: "client"
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    
volumes:
  db:
