
version: "3.8"

services:
  mongo_db:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  tcapi:
    depends_on:
      - mongo_db
    image: tcarisland/tcapi:latest
    ports:
      - 8081:8080

volumes:
  db: