
version: "3.8"

services:
  mongo_db:
    platform: linux/x86_64
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  tcapi:
    platform: linux/x86_64
    depends_on:
      - mongo_db
    image: tcarisland/tcapi:latest
    restart: on-failure
    ports:
      - 8081:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: